# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/bluele/gcache"

[[constraint]]
  name = "github.com/gorilla/feeds"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/hackebrot/turtle"

[[constraint]]
  name = "github.com/mssola/user_agent"
  version = "0.4.1"

[[constraint]]
  branch = "develop"
  name = "github.com/parnurzeal/gorequest"

[[constraint]]
  name = "github.com/qiniu/api.v7"
  version = "7.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/vinta/pangu"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.0"

[[constraint]]
  name = "gopkg.in/russross/blackfriday.v2"
  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
